spring:
  application:
    name: adminapi
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://10.10.10.228:13306/localeadmin
    username: localeadmin
    password: localeadmin

    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      connection-timeout: 5000

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MariaDB103Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 20MB
      location: upload
      enabled: true

org:
  oz:
    accessTime: 3
    refreshTime: 10
    alwaysNew: true
    upload:
      path: upload

logging:
  level:
    org.springframework.security.web: TRACE
    org.oz.adminapi.localmaneger: TRACE